### ISSUE TITLE
macのSafariでドラッグ(選択状態に)される

### ISSUE THREAD

**Issue by tenzyu** [HiraginoYuki/15-puzzle.app#2]
本題: 忘れないためのメモ

問題: ピースを移動させるためにクリックしていると、高頻度で(ドラッグ時のような)選択状態にされる。これは、マウスを動かさずにクリックをしているだけでも起きるので、一種のバグと思われる。

**Comment by hiraginoyuki** [comment]
もう修正コミットしちゃったんだよね

**Comment by hiraginoyuki** [comment]
https://github.com/HiraginoYuki/fifteen-puzzle/commit/b2075a219c5880e16a2263ddd809b3de86edff43

**Comment by hiraginoyuki** [comment]
とじるね
