### ISSUE TITLE
スマートフォン向けに画面上にリセットボタンを配置

### ISSUE THREAD

**Issue by Assault1892** [HiraginoYuki/15-puzzle.app#20]
PC では Space キーを押すだけで即リセットが可能ですが、スマートフォンでは一度 Solve しないとリセットができません。
開幕でミスしたり、目標を達成できなかった際に即時リセットできるよう、リセットボタンの配置をお願いします。

**Comment by hiraginoyuki** [comment]
implement it yourself cuz i don't need it

**Comment by Assault1892** [comment]
dumbass

**Comment by hiraginoyuki** [comment]
what
