### ISSUE TITLE
大文字やんけ

### ISSUE THREAD

**Issue by hiraginoyuki** [HiraginoYuki/15-puzzle.app#46]
https://github.com/hiraginoyuki/webpack.15-puzzle.app/blob/master/src/app/app.tsx#L14

**Comment by Mogyuchi** [comment]
わろた
なぜ抜けた

**Comment by hiraginoyuki** [comment]
わからん
やばいな

**Comment by hiraginoyuki** [comment]
いや、なおしたの[こっち](https://github.com/hiraginoyuki/15-puzzle/pull/16)だわ

**Comment by Mogyuchi** [comment]
わろた
