### ISSUE TITLE
左下「Made by Yuki Hiragino」表記のリンク追加

### ISSUE THREAD

**Issue by Assault1892** [HiraginoYuki/15-puzzle.app#9]
[15パズル](https://15-puzzle.app/) の画面左下「Made by Yuki Hiragino」テキストを、
この [リポジトリ](https://github.com/HiraginoYuki/fifteen-puzzle) か、 [ヒラギノの GitHub リンク](https://github.com/HiraginoYuki) に飛ぶようにするのよさそう。
単なるテキスト表示だと（少なくとも自分は）味気ないと感じるし、 GitHub のリンクに飛べたりしたら
15パズルのソースがどうなっているか、気になる人にとっては助かる存在だと思う。

![fifteen-puzzle_issue_text](https://user-images.githubusercontent.com/34514603/108109770-b3186f00-70d5-11eb-8b72-360eaffe35ab.png)

**Comment by hiraginoyuki** [comment]
それ、作るときに思ったんだが、どっちにするか永遠に決められなかったのでやめた
今思うと、ユーザーからリポジトリへ飛ぶより、リポジトリからユーザーに飛ぶ方が圧倒的に楽なので、リポジトリのURLを追加しようと思う

**Comment by Assault1892** [comment]
なんなら左下押したらリセットでもええんやで〜

**Comment by hiraginoyuki** [comment]
nope

**Comment by Assault1892** [comment]
why

**Comment by hiraginoyuki** [comment]
a85092788f78abc64be1b49d9d7cbe22433685d8

**Comment by hiraginoyuki** [comment]
ちな、忘れてた
